[project]
name = "l2-googledrive"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django>=5.1.5",
    "djlint>=1.36.4",
    "pillow>=11.1.0",
]
